//
//  Client+Callbacks.swift
//  DiscordTry5
//
//  Created by Christian Norton on 3/30/26.
//

@_implementationOnly import discord_partner_sdk

extension DiscordClient {

    private func registerStatusChangedBridge() {
        let bridge: StatusChangedCallback = { [weak self] result in
            guard let self else { return }
            self.dispatchStatusCallbacks(result)
        }

        let ptr = setCallback(bridge, to: \.statusChangedBridge)
        usingLock(
            Discord_Client_SetStatusChangedCallback,
            statusChangedTrampoline,
            nil,
            ptr
        )
    }

    /// Adds a callback function to be invoked for each new log message generated by the SDK.
    ///
    /// This function excludes most logs related to voice and WebRTC activity, as those tend to be
    /// significantly more verbose and may require a different logging level. Instead, it includes
    /// logs for systems such as lobbies, relationships, presence, and authentication.
    ///
    /// It is strongly recommended to invoke this function immediately after constructing the Client
    /// object.
    ///
    /// - Parameters:
    ///   - severity: The minimum logging severity to receive.
    ///   - body: Callback invoked for each log message.
    public func onLog(
        of severity: LoggingSeverity = .info,
        _ body: @escaping LogCallback
    ) {
        let ptr = setCallback(body, to: \.log)
        storage.withLock { raw in
            Discord_Client_AddLogCallback(
                &raw,
                logTrampoline,
                nil,
                ptr,
                severity.discordValue
            )
        }
    }
    
    /// Adds a callback function to be invoked for each new log message generated by the
    /// voice subsystem of the SDK, including the underlying webrtc infrastructure.
    ///
    /// We strongly recommend invoking this function immediately after constructing the Client object.
    ///
    /// - Parameters:
    ///   - severity: The minimum logging severity to receive.
    ///   - body: Callback invoked for each log message.
    public func onVoiceLog(
        of severity: LoggingSeverity = .info,
        _ body: @escaping LogCallback
    ) {
        let ptr = setCallback(body, to: \.voiceLog)
        storage.withLock { raw in
            Discord_Client_AddVoiceLogCallback(
                &raw,
                logTrampoline,
                nil,
                ptr,
                severity.discordValue
            )
        }
    }
    
    /// Callback to be invoked whenever the SDKs status changes.
    public func onStatusChanged(
        _ body: @escaping StatusChangedCallback
    ) {
        _ = setCallback(body, to: \.statusChanged)
        registerStatusChangedBridge()
    }

    /// Callback to be invoked whenever the client reaches ``ClientStatus/ready``.
    ///
    /// If the client is already ready when this is registered, the callback is invoked immediately.
    public func onReady(
        _ body: @escaping ReadyCallback
    ) {
        _ = setCallback(body, to: \.ready)
        registerStatusChangedBridge()

        if status == .ready {
            body()
        }
    }
    
    /// Fetches basic information about the user associated with the given auth token.
    ///
    /// This can allow you to check if an auth token is valid or not.
    /// This does not require the client to be connected or to have it's own authentication token,
    /// so it can be called immediately after the client connects.
    public func fetchCurrentUser(token: String, type: AuthorizationTokenType, _ body: @escaping FetchCurrentUserCallback) {
        let cb = CallbackBox(body)
        token.withDiscordString { str in
            usingLock(
                Discord_Client_FetchCurrentUser,
                type.discordValue,
                str,
                fetchCurrentUserTrampoline,
                freeBox,
                cb.retainedOpaqueValue()
            )
        }
    }
    
    /// Opens the Connected Games settings in the Discord client, where users can manage
    /// settings related to games using the Discord Social SDK.
    ///
    /// If the client is not connected or the user is using a provisional account,
    /// this function does nothing.
    ///
    /// This function is always a no-op on console platforms.
    ///
    /// - Parameter body: Callback invoked after attempting to open the Connected Games settings.
    public func openConnectedSettings(
        _ body: @escaping OpenConnectedGamesSettingsInDiscordCallback
    ) {
        let cb = CallbackBox(body)
        usingLock(
            Discord_Client_OpenConnectedGamesSettingsInDiscord,
            openConnectedGameSettingsTrampoline,
            freeBox,
            cb.retainedOpaqueValue()
        )
    }
    
    /// Checks whether the Discord mobile app is installed on this device.
    /// On desktop platforms, always returns false.
    ///
    /// This check does not require a client connection and can be called at any time.
    ///
    /// This can be used to provide UI hints to users about whether they can authorize via the
    /// Discord app, or whether they will need to use a web browser flow.
    ///
    /// Platform Requirements:
    /// - iOS: Your app must include "discord" in the LSApplicationQueriesSchemes array
    ///   in your Info.plist for this check to work correctly.
    /// - Android: Your app must include "com.discord" in the `queries` element
    ///   in your AndroidManifest.xml (required for Android 11+).
    @available(iOS 18.5, *)
    @available(Android 11.0, *)
    public func isDiscordInstalled(
        _ body: @escaping IsDiscordAppInstalledCallback
    ) {
        let cb = CallbackBox(body)
        usingLock(
            Discord_Client_IsDiscordAppInstalled,
            appInstalledTrampoline,
            freeBox,
            cb.retainedOpaqueValue()
        )
    }
    
    /// If the Discord app is running on the user's computer and the SDK establishes a
    /// connection to it, this function will return the user that is currently logged in to the Discord app.
    @available(*, renamed: "clientConnectedUser(for:)")
    public func clientConnectedUser(for application: UInt64, _ body: @escaping GetDiscordClientConnectedUserCallback) {
        let cb = CallbackBox(body)
        usingLock(
            Discord_Client_GetDiscordClientConnectedUser,
            application,
            connectedClientTrampoline,
            freeBox,
            cb.retainedOpaqueValue()
        )
    }

}
