//
//  Client+LobbyGuild.swift
//  DiscordTry5
//
//  Created by Christian Norton on 3/30/26.
//

@_implementationOnly import discord_partner_sdk

public extension DiscordClient {
    
    /// Retrieves recent messages from the specified lobby.
    ///
    /// Returns a list of ``MessageHandle`` representing recent messages in the lobby,
    /// with a maximum of 200 messages and up to 72 hours of history.
    /// Messages are returned in reverse chronological order (newest first).
    /// This function requires the current user to be a member of the lobby.
    ///
    /// Note: This function makes an HTTP request to Discord’s API to retrieve messages,
    /// rather than only returning messages cached locally by the SDK.
    ///
    /// Retrieves recent messages from the specified lobby with the given limit.
    ///
    /// - Parameters:
    ///   - id: The identifier of the lobby.
    ///   - limit: The maximum number of messages to retrieve.
    ///   - body: Callback invoked with the resulting messages or an error.
    func getLobbyMessagesWithLimit(
        id: UInt64,
        limit: Int32,
        _ body: @escaping GetLobbyMessagesCallback
    ) {
        let cb = CallbackBox(body)
       	usingLock(
            Discord_Client_GetLobbyMessagesWithLimit,
            id,
            limit,
            lobbyMessagesTrampoline,
            freeBox,
            cb.retainedOpaqueValue()
        )
    }
    
    
    /// Sends a message in a lobby chat to all members of the lobby.
    ///
    /// The content of the message is restricted to a maximum of 2,000 characters.
    /// See https://discord.com/developers/docs/resources/message for more details.
    ///
    /// The content of the message can include special markup for formatting if desired.
    /// See https://discord.com/developers/docs/reference#message-formatting for more details.
    ///
    /// If the lobby is linked to a channel, the message will also be sent to that
    /// channel on Discord.
    ///
    /// - Parameters:
    ///   - id: The identifier of the lobby.
    ///   - content: The message content to send.
    ///   - body: Callback invoked with the result of the send operation.
    func sendLobbyMessage(
        id: UInt64,
        content: String,
        _ body: @escaping SendUserMessageCallback
    ) {
        let cb = CallbackBox(body)
        content.withDiscordString { str in
            usingLock(
                Discord_Client_SendLobbyMessage,
                id,
                str,
                sendUserMessageTrampoline,
                freeBox,
                cb.retainedOpaqueValue()
            )
        }
    }
    
    /// Variant of ``sendLobbyMessage(id:content:_:)`` that also accepts metadata to be sent with the message.
    ///
    /// Metadata is just simple string key/value pairs.
    /// An example use case for this might be to include the name of the character that sent a
    /// message.
    func sendLobbyMessage(
        to lobby: UInt64,
        message: String,
        metadata: [String: String],
        _ body: @escaping SendUserMessageCallback
    ) {
        let cb = CallbackBox(body)
        message.withDiscordString { str in
            metadata.withDiscordProperties { props in
                usingLock(
                    Discord_Client_SendLobbyMessageWithMetadata,
                    lobby,
                    str,
                    props,
                    sendUserMessageTrampoline,
                    freeBox,
                    cb.retainedOpaqueValue()
                )
            }
        }
    }
    
    /// Joins the user to the specified lobby, creating one if it does not exist.
    ///
    /// The lobby is identified by the provided secret string, which should be a hard-to-guess value
    /// generated by the game. All users who join with the same secret will be placed in the same lobby.
    ///
    /// For exchanging the secret, it is strongly recommended to use activity invites or rich presence
    /// systems, which allow you to include a secret string that only accepted party members can access.
    ///
    /// As with server-created lobbies, client-created lobbies are automatically deleted after being
    /// idle for a few minutes (currently around 5 minutes). A lobby is considered idle when no users
    /// are connected to it.
    ///
    /// This function should not be used for long-lived lobbies. The secret value expires after
    /// approximately 30 days, after which the existing lobby can no longer be joined and a new one
    /// will be created instead.
    ///
    /// - Parameters:
    ///   - secret: A hard-to-guess string used to identify and join the lobby.
    ///   - body: Callback invoked with the result of creating or joining the lobby.
    func createOrJoinLobby(
        secret: String,
        _ body: @escaping CreateOrJoinLobbyCallback
    ) {
        let cb = CallbackBox(body)
        secret.withDiscordString { str in
            usingLock(
                Discord_Client_CreateOrJoinLobby,
                str,
                createOrJoinLobbyTrampoline,
                freeBox,
                cb.retainedOpaqueValue()
            )
        }
    }
    
    /// Joins the user to the specified lobby, creating one if it does not exist.
    ///
    /// The lobby is specified by the supplied string, which should be a hard to guess secret
    /// generated by the game. All users who join the lobby with the same secret will be placed in
    /// the same lobby.
    ///
    /// For exchanging the secret, we strongly encourage looking into the activity invite and rich
    /// presence systems which provide a way to include a secret string that only accepted party
    /// members are able to see.
    ///
    /// As with server created lobbies, client created lobbies auto-delete once they have been idle
    /// for a few minutes (which currently defaults to 5 minutes). A lobby is idle if no users are
    /// connected to it.
    ///
    /// This function shouldn't be used for long lived lobbies. The "secret" value expires after ~30
    /// days, at which point the existing lobby cannot be joined and a new one would be created
    /// instead.
    func createOrJoinLobby(
        secret: String,
        lobby: [String: String],
        member: [String: String],
        _ body: @escaping CreateOrJoinLobbyCallback
    ) {
        let cb = CallbackBox(body)
        secret.withDiscordString { str in
            lobby.withDiscordProperties { lobbyProps in
                member.withDiscordProperties { memberProps in
                    usingLock(
                        Discord_Client_CreateOrJoinLobbyWithMetadata,
                        str,
                        lobbyProps,
                        memberProps,
                        createOrJoinLobbyTrampoline,
                        freeBox,
                        cb.retainedOpaqueValue()
                    )
                }
            }
        }
    }
    
    /// Fetches all channels that the current user can access in the specified guild.
    ///
    /// Channels are sorted by their `position` field, which matches the ordering shown
    /// in the Discord client.
    ///
    /// The purpose of this function is to support the channel linking flow, allowing a
    /// Discord channel to be linked to an in-game lobby. It can be used to power a UI
    /// where the user selects a channel after choosing a guild. See the documentation
    /// for ``LobbyHandle`` for more information.
    ///
    /// - Parameters:
    ///   - guildId: The identifier of the guild.
    ///   - body: Callback invoked with the list of accessible channels.
    func guildChannels(
        for guildId: UInt64,
        _ body: @escaping GetGuildChannelsCallback
    ) {
        let cb = CallbackBox(body)
        usingLock(
            Discord_Client_GetGuildChannels,
            guildId,
            guildChannelsTrampoline,
            freeBox,
            cb.retainedOpaqueValue()
        )
    }
    
    /// Fetches all guilds (Discord servers) that the current user is a member of.
    ///
    /// The purpose of this function is to support the channel linking flow for linking a
    /// Discord channel to an in-game lobby. It can be used to power a UI that allows the
    /// user to select which guild to link to. See the documentation for ``LobbyHandle``
    /// for more information.
    ///
    /// - Parameter body: Callback invoked with the list of guilds.
    func userGuilds(
        _ body: @escaping GetUserGuildsCallback
    ) {
        let cb = CallbackBox(body)
        usingLock(
            Discord_Client_GetUserGuilds,
            userGuildsTrampoline,
            freeBox,
            cb.retainedOpaqueValue()
        )
    }
    
    /// Invites the current user to the Discord guild of the channel linked to the specified lobby.
    ///
    /// The user is forwarded to the Discord client with the resulting invite URL, where they can
    /// choose to accept or decline the invitation.
    ///
    /// On console platforms, the user is not navigated to a Discord client. In this case, the invite
    /// URL should be presented to the user so they can use it manually.
    ///
    /// - Parameters:
    ///   - id: The identifier of the lobby.
    ///   - provisionalMerge: Callback invoked if a provisional account merge is required.
    ///   - body: Callback invoked with the result of the join operation.
    func joinLinkedLobbyGuild(
        for id: UInt64,
        provisionalMerge: @escaping ProvisionalUserMergeRequiredCallback,
        body: @escaping JoinLinkedLobbyGuildCallback
    ) {
        let pCb = CallbackBox(provisionalMerge)
        let bCb = CallbackBox(body)
        
        usingLock(
         	Discord_Client_JoinLinkedLobbyGuild,
            id,
            provisionalUserMergeTrampoline,
            freeBox,
            pCb.retainedOpaqueValue(),
            joinLinkedLobbyTrampoline,
            freeBox,
            bCb.retainedOpaqueValue()
        )
    }
    
    /// Removes the current user from the specified lobby.
    ///
    /// Only lobbies that contain a "secret" can be left.
    /// In other words, only lobbies created with `createJoinLobby` can be left.
    /// Lobbies created using the server API may not be manipulated by clients, so you must
    /// use the server API to remove them as well.
    ///
    /// - Parameters:
    ///   - id: The identifier of the lobby to leave.
    ///   - body: Callback invoked with the result of the leave operation.
    func leaveLobby(
        _ id: UInt64,
        _ body: @escaping LeaveLobbyCallback
    ) {
        let cb = CallbackBox(body)
        usingLock(
            Discord_Client_LeaveLobby,
            id,
            leaveLobbyTrampoline,
            freeBox,
            cb.retainedOpaqueValue()
        )
    }
    
    /// Links the specified Discord channel to the specified in-game lobby.
    ///
    /// Any message sent in one will be mirrored to the other.
    /// See the documentation for ``LobbyHandle`` for more information.
    ///
    /// - Parameters:
    ///   - channel: The identifier of the Discord channel.
    ///   - lobby: The identifier of the in-game lobby.
    ///   - body: Callback invoked with the result of the link operation.
    func linkChannelToLobby(
        channel: UInt64,
        lobby: UInt64,
        _ body: @escaping LinkOrUnlinkChannelCallback
    ) {
        let cb = CallbackBox(body)
        usingLock(
            Discord_Client_LinkChannelToLobby,
            channel,
            lobby,
            linkUnlinkChannelTrampoline,
            freeBox,
            cb.retainedOpaqueValue()
        )
    }
    
    /// Removes any existing channel link from the specified lobby.
    ///
    /// See the documentation for ``LobbyHandle`` for more information.
    /// A lobby can be unlinked by any user with the ``LobbyMemberFlags.CanLinkLobby`` flag. The user
    /// does not need to have permissions on the Discord channel to remove the in-game link.
    ///
    /// - Parameters:
    ///   - lobby: The identifier of the lobby.
    ///   - body: Callback invoked with the result of the unlink operation.
    func unlinkChannelFromLobby(
        lobby: UInt64,
        _ body: @escaping LinkOrUnlinkChannelCallback
    ) {
        let cb = CallbackBox(body)
        usingLock(
            Discord_Client_UnlinkChannelFromLobby,
            lobby,
            linkUnlinkChannelTrampoline,
            freeBox,
            cb.retainedOpaqueValue()
        )
    }
    
    /// Sets a callback to be invoked when a lobby becomes available to the client.
	///
	/// A lobby can become available in several situations:
	/// - A new lobby is created and the current user is a member.
	/// - The current user is added to an existing lobby.
	/// - A lobby recovers after a backend crash and becomes available again.
	///
	/// This means the callback can be invoked more than once in a single session.
	/// Typically, it should not be invoked twice consecutively. For example, if a lobby
	/// crashes or the user is removed, you should expect the corresponding deletion
	/// callback to be invoked first.
	///
	/// - Parameter body: Callback invoked when a lobby becomes available.
    func onLobbyCreated(
        _ body: @escaping LobbyCreatedCallback
    ) {
        let ptr = setCallback(body, to: \.lobbyCreated)
        usingLock(
            Discord_Client_SetLobbyCreatedCallback,
            lobbyCreatedTrampoline,
            nil,
            ptr
        )
    }
    
    /// Sets a callback to be invoked when a lobby is no longer available.
    ///
    /// This callback can be invoked in several situations:
    /// - A lobby the user is a member of is deleted.
    /// - The current user is removed from a lobby.
    /// - A backend failure causes the lobby to become unavailable.
    ///
    /// This callback may be invoked even if the lobby still exists for other users.
    ///
    /// - Parameter body: Callback invoked when a lobby becomes unavailable.
    func onLobbyDeleted(
        _ body: @escaping LobbyDeletedCallback
    ) {
        let ptr = setCallback(body, to: \.lobbyDeleted)
        usingLock(
            Discord_Client_SetLobbyDeletedCallback,
            lobbyDeletedTrampoline,
            nil,
            ptr
        )
    }
    
    /// Sets a callback to be invoked when a lobby is updated, such as when its metadata changes.
    ///
    /// - Parameter body: Callback invoked when a lobby is modified.
    func onLobbyUpdated(
        _ body: @escaping LobbyUpdatedCallback
    ) {
        let ptr = setCallback(body, to: \.lobbyUpdated)
        usingLock(
            Discord_Client_SetLobbyUpdatedCallback,
            lobbyUpdatedTrampoline,
            nil,
            ptr
        )
    }
    
    /// Sets a callback function to be invoked whenever a user is added to a lobby.
    ///
    /// This callback is not invoked when the current user is added to a lobby. In that case,
    /// the `onLobbyCreated` callback is invoked instead. Additionally, the SDK distinguishes
    /// between lobby membership and connection state. A user being added does not necessarily
    /// mean they are currently online or connected, only that they have permission to join.
    ///
    /// - Parameter body: Callback invoked when a user is added to a lobby.
    func onLobbyMemberAdded(
        _ body: @escaping LobbyMemberAddedCallback
    ) {
        let ptr = setCallback(body, to: \.lobbyMemberAdded)
        usingLock(
            Discord_Client_SetLobbyMemberAddedCallback,
            lobbyMemberAddedTrampoline,
            nil,
            ptr
        )
    }
    
    /// Sets a callback function to be invoked whenever a member of a lobby is removed
    /// and can no longer connect to it.
    ///
    /// This callback is not invoked when the current user is removed from a lobby. In that case,
    /// the `onLobbyDeleted` callback is invoked instead. This callback is also not triggered when
    /// a user simply exits the game. In that scenario, `onLobbyMemberUpdated` is invoked, and the
    /// ``LobbyMemberHandle`` will indicate that the user is no longer connected.
    ///
    /// - Parameter body: Callback invoked when a user is removed from a lobby.
    func onLobbyMemberRemoved(
        _ body: @escaping LobbyMemberRemovedCallback
    ) {
        let ptr = setCallback(body, to: \.lobbyMemberRemoved)
        usingLock(
            Discord_Client_SetLobbyMemberRemovedCallback,
            lobbyMemberRemovedTrampoline,
            nil,
            ptr
        )
    }
    
    /// Sets a callback function to be invoked whenever a member of a lobby is updated.
    ///
    /// This callback is invoked when:
    /// - A user connects or disconnects.
    /// - The metadata of a member changes.
    ///
    /// - Parameter body: Callback invoked when a lobby member is updated.
    func onLobbyMemberUpdated(
        _ body: @escaping LobbyMemberUpdatedCallback
    ) {
        let ptr = setCallback(body, to: \.lobbyMemberUpdated)
        usingLock(
            Discord_Client_SetLobbyMemberUpdatedCallback,
            lobbyMemberUpdatedTrampoline,
            nil,
            ptr
        )
    }
    
}
